Fix TensorFlow stdlib module compilation. (#546)
Follow-up to https://github.com/tensorflow/swift-apis/pull/540 fixing
TensorFlow stdlib module compilation.

- Rename `Sources/Tensor/Utilities.swift -> Sources/Tensor/TensorUtilities.swift`
  to fix stdlib compilation error: `filename "Utilities.swift" used twice`.

- Add `#if !COMPILING_TENSORFLOW_STDLIB_MODULE` guards gating `import Tensor`
declarations so that the TensorFlow module can be built as part of the stdlib.
  - This will no longer be necessary when TensorFlow is no longer built as
    part of the stdlib: https://github.com/tensorflow/swift-apis/issues/488.