Fix bug in `batchGathering`
Previously, if `batchGathering` was operating upon a batch of data, it would get
stuck during the final reshape, due to using the wrong input tensor shape. This
change fixes that and includes a test case that caught the bug before the fix was
applied.

```
Test Case '-[TensorFlowTests.BasicOperatorTests testBatchGatheringAcrossBatch]' started.
Fatal error: Input to reshape is a tensor with 6 values, but the requested shape has 3: file /Users/saeta/src/swift-apis/Sources/TensorFlow/Bindings/EagerExecution.swift, line 301
Exited with signal code 4
```